### PR TITLE
remove 7zip libraries

### PR DESCRIPTION
**Pull request by Jan200101**
beans distributes the game in a zstd compressed tarball and the 7zip libraries are only loaded at runtime when needed.

If this is a problem butler has a seemingly undocument [`fetch-7z-libs`](https://github.com/itchio/butler/blob/50d55e90a90f4d03b5cfc7d35d135b30584c91a7/cmd/extract/extract.go#L33) command that they use to generate the release builds.

Tested on Linux.

### CODE REVIEW

**Comment by Jan200101** [comment]
> Has the verify, and update commands been verified that they with with this change?

I have tried install and vaguely remember running verify and not seeing any errors.

Will test update ASAP.

> I'm not sure if butler uses 7z internally, and I'd like to make sure that everything works (not just compiles).

Its not needed by butler itself but by [`szextractor`](https://github.com/itchio/boar/tree/master) which is a part of the `boar` module and used to only deal with 7z extraction.

If there is still worry I can simply add the call to `fetch-7z-libs` which will download them from itch and put them next to the binary.

**Comment by ktwrd** [comment]
> I have tried install and vaguely remember running verify and not seeing any errors.
> 
> Will test update ASAP.

Install only uses the `tar` and `zstd` crates, and doesn't go near butler (except to verify the game files after install). The `update` subcommand uses the `.pwr` file format for patching, which might use 7zip internally, but I'm not 100% sure.


> Its not needed by butler itself but by [`szextractor`](https://github.com/itchio/boar/tree/master?rgh-link-date=2024-06-07T06%3A50%3A34Z) which is a part of the `boar` module and used to only deal with 7z extraction.
> 
> If there is still worry I can simply add the call to `fetch-7z-libs` which will download them from itch and put them next to the binary.

Sounds good, please make sure that it's called directly after `butler` has been written to disk, and the libraries are extracted to the temp folder that butler is written to.

**Comment by Jan200101** [comment]
Tested updating which worked without the libraries in place.
I'll still add the command to fetch the 7z libs.

**Comment by ktwrd** [comment]
Looks good to me.

**Pull request merged**
