### PR TITLE
Housekeeping/clippy 1

### PR DESCRIPTION
**Pull request by toastxc**
Hello bean enjoyers!
I have decided to clean up bean-rs a bit, its mostly readability and conciseness issues.
And the occasional illogical bits of code (e.g. `x = y * 0`).

There are a few more warnings from the linter but I'm unsure on how to proceed with those, or if they're even worth perusing.

### CODE REVIEW

**Comment by toastxc** [comment]
The most common existing warning is [Err`-variant returned from this function is very large](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err). 

Specifically the  `AppVarDataSerializeFailure` and `ButlerVerifyFailure` variants of BeansError  are beyond the recommended maximum size.

I'd like to know what y'all think is the best course of action for this.

**Comment by ktwrd** [comment]
> ...
> I'd like to know what y'all think is the best course of action for this.

The main reason why the `BeansError` enum is so massive is because it's the main error type for `beans-rs` and it has so many error types because we want to catch as many codeflow-breaking things and tell the user what went wrong so it's easy to debug (and we want to display a unique message with `thiserror`).

Those errors are also written (most of the time) to `log::trace!` so it's visible in the Sentry breadcrumbs, and we want to have whatever information that is used at that point in those variants.

**Comment by toastxc** [comment]
One solution is boxing the Error variant (or possibly reducing the size of `beanserror` variants). But that might be something to work on later.  

Changes should have no impact on functionality, ready to merge.

**Comment by toastxc** [comment]
For now the warnings will just be ignored.

**Comment by ktwrd** [comment]
Made some changes to `rustfmt.toml` so it's more in-line with linting styles based off my current/previous projects.

**Review by ktwrd — APPROVED** [review]

**Pull request merged**
