### PR TITLE
Uninstall Workflow

### PR DESCRIPTION
**Pull request by ktwrd**
This PR adds an `uninstall` CLI sub-command and wizard option for uninstalling the target game. Before deleting the sourcemod mod folder, it will check if all of the following conditions are met;
- Is the game actually installed (`RunnerContext.current_version.is_some()`)
- Is the game not running (with `crate::helper::is_game_running` where `mod_directory` is from `RunnerContext.get_mod_location()`)

If any of those conditions are *not* met, an error will be returned and will not allowed the user to uninstall the game (if it is even installed).

### CODE REVIEW

**Comment by toastxc** [comment]
I'll have a looky

**Comment by toastxc** [comment]
I can't see anything inherently wrong with the modifications, but do make sure to test (and not do a crowdstrike).

**Review by toastxc — DISMISSED** [review]
Looks good, pls test (including edge cases).

**Comment by ktwrd** [comment]
> Looks good, pls test (including edge cases).

I tested it on W10 (w/ OF in the default sourcemod folder) last night, but I'll check it on my Debian install and my Steam Deck tonight.

**Comment by ktwrd** [comment]
Tested on my windows install. Need to rebase from develop since #30 was merged.

**Review by toastxc — DISMISSED** [review]
looks good

**Review by toastxc — APPROVED** [review]
compiles fine

**Pull request merged**
