### PR TITLE
Housekeeping/clippy 2

### PR DESCRIPTION
**Pull request by toastxc**

### CODE REVIEW

**Comment by toastxc** [comment]
You're gonna want to look at the recent commits.
they are less indented but you may not like it

**Comment by ktwrd** [comment]
Looks good except that in `crate::extract::unpack_tarball`, `pb.finish();` is never called which will will cause issues.

this should be called if the function returns at any point after the progress bar is created.

**Comment by toastxc** [comment]
I'd like to add that this is a draft: will complete laterrrrr.

**Comment by ktwrd** [comment]
> I'd like to add that this is a draft: will complete laterrrrr.

then make the PR a draft 🤓

**Comment by ktwrd** [comment]
@toastxc Resolved merge conflicts :3

**Review by ktwrd — APPROVED** [review]

**Pull request merged**
